version: v0.{build}-alpha
build:
  verbosity: detailed
configuration: Release
install:
  git submodule update --init --recursive
build_script: C:\projects\urat\uRAT.sln
artifacts:
  - path: build
    name: binaries
deploy:
  - provider: GitHub
    draft: false
    prerelease: true
    auth_token:
      secure: hja8VUbSzRtmchGX7pZ1TWlyKMqXjAVVU9G3EafwWJQPUMzgeSCknXaviLXacWKz
    on:
      branch: test
      appveyor_repo_tag: false